### ISSUE TITLE
Is it possible to build libmega without sqlite?

### ISSUE THREAD

**Issue by zenden2k** [meganz/sdk#1138]
I am trying to build libmega without **sqlite**  on Linux Mint 18 (64 bit):

```
git clone https://github.com/meganz/sdk.git
cd sdk
sh autogen.sh
./configure --without-sqlite
``` 

also I have tried `./configure --with-sqlite=no`

I get an error:

```
checking for SQLite... no
checking for Berkeley DB... --with-db not specified
configure: Using SQLite3 as the default DB access layer.
checking sqlite3.h usability... no
checking sqlite3.h presence... no
checking for sqlite3.h... no
configure: error: sqlite3.h header not found or not usable
```

Is it optional or required package?

**Comment by WitalijBukatkin** [comment]
./configure --without-sqlite

**Comment by sergiohs84** [comment]
The short answer is NO, *sqlite* is mandatory for the MEGA SDK.
The long answer is that the SDK could work without cache, but it would turn into a suboptimal piece of software, since it would require to load the whole account's state upon every app's startup. Hence, a DB backend support is highly recommended. Unfortunately, the Berkeley DB is no longer supported, so you should configure the library with SQLite support.
