### ISSUE TITLE
startUpload  is it possible from memory stream?

### ISSUE THREAD

**Issue by dima72** [meganz/sdk#120]
Dear All,

Is it possible in megaapi upload file directly from memory without reference to a physical file?

thanks,

**Comment by javiserrano** [comment]
Hello, it's possible to do it if the size of the file is known. However, it isn't implemented yet in our SDK.
Another user with a similar need has had a partial success with his own implementation of the filesystem layer:
https://github.com/meganz/sdk/issues/78

We should implement that feature at some point, but I can't give you an ETA yet.

**Comment by dima72** [comment]
OK, thanks,
I'll be waiting for the opportunity to upload from memory.

download into memory works fine though.

**Comment by dima72** [comment]
Javi,
thank you very much for the SDK support and we are implemented most of the features to integrate our product with MEGA. For the moment we use stream to save into temp file and then upload from temp file, thus this becomes a bottleneck,
We will highly appreciate if you add to MEGA SDK upload from memory feature .

thanks,

**Comment by dima72** [comment]
up

**Comment by javiserrano** [comment]
Hi.

We have made some progress in this sense but there isn't anything usable yet.
We have added a new interface (`InputStreamAccess`) that has a corresponding one in the intermediate layer (`MegaInputStream`) and allows the creation of `FileFingerprints` using it. At the moment, we use this function to improve the `Camera Uploads` feature in our mobile apps to check if images have been already uploaded (using `MegaApi::getFingerprint(MegaInputStream *inputStream, int64_t mtime)` and `MegaApi::getNodeByFingerprint`), especially in platforms in which image files can't be directly accessed..

Our idea is to allow uploads from these new interfaces in the future.

**Comment by dima72** [comment]
Thanks for progress Javi,
I will be waiting for completion of Upload from Stream.

**Comment by dima72** [comment]
Any news on the issue?

**Comment by javiserrano** [comment]
Yes. I have pushed the code that we have until now in the `upload-from-inputstream` branch:
https://github.com/meganz/sdk/tree/upload-from-inputstream

It's still experimental and have some inconveniences, but it works in our initial tests. The main inconveniences are:
- Uploaded files don't have an encrypted fingerprint (this disables some optimizations in the sync engine, but it's not a major issue).
- Uploaded images don't have an attached thumbnail/previews.The SDK saves an (encrypted) thumbnail/preview of each image in MEGA to show it in client apps, but this is not possible at the moment for streaming transfers.

Feel free to test the new `startUpload` method in `MegaApi` and give us your feedback. Unfortunately, we can't focus on this feature in this moment, so I think that it won't be available in the `master` branch until the next month.

**Comment by dima72** [comment]
Dear Javi,
thank you for update, I apologies for late response.

when I'm trying to rebuild my code with new mega.lib, I'm getting:
>mega.lib(sqlite.obj) : error LNK2001: unresolved external symbol _sqlite3_exec
1>mega.lib(sqlite.obj) : error LNK2001: unresolved external symbol _sqlite3_open
1>mega.lib(sqlite.obj) : error LNK2001: unresolved external symbol _sqlite3_close
...etc.
thus I have sqlite.cpp attached to mega.lib project and compiled well.

thanks in advance for any suggestions,

**Comment by dima72** [comment]
Dea Javi,

thank you for the new SDK, in mean time can you please explain
why sqllite3.dll is added to the project. I can see that our software can not compile without sqllite.lib
and can not run without sqllite3.dll

Respectfully,

**Comment by dima72** [comment]
Dear Javi,

 new startUpload method seems dos not work.

first let me note:
memblock = new char [1000];
inputStream->read( memblock, 1000 );
int64_t sz = inputStream->getSize();		
			
inputStream->getSize() always returns zero.
 	
megaApi->startUpload does something but there is no files on remote as result.

Respectfully,

**Comment by dima72** [comment]
Dear Javi,
please commit the latest upload-from-inputstream
to https://github.com/meganz/sdk/blob/upload-from-inputstream/src/megaapi.cpp

it is definitely a mock code in current version
int64_t MegaInputStream::getSize()
{
    return 0;
}

bool MegaInputStream::read(char *buffer, size_t size)
{
    return false;
}
Respectfully,

**Comment by javiserrano** [comment]
Hi,

`MegaInputStream` is just an interface that you have to implement according to your own needs. We can't create a `MegaInputStream` for everybody because there are many possible sources of data (memory buffer, sockets, an output stream, ....).

It has a default (useless) implementation because SWIG requires it to generate bindings for some programming languages.

You have an example implementation of the `MegaInputStream` interface here (`FileInputStream`):
https://github.com/meganz/sdk/blob/upload-from-inputstream/src/megaapi_impl.cpp#L10296

That is the implementation that we have used for testing.

**Comment by dima72** [comment]
thank you for suggestion Javi,

now it works!

**Comment by dima72** [comment]
Dear Mega Developers,
how probable is to include the startUpload method into current trunk?
the [](https://github.com/meganz/sdk/tree/upload-from-inputstream) is too old.

thanks in advance,

**Comment by javiserrano** [comment]
It would be very very difficult because the SDK has changed a lot since the creation of that branch.
So I have made a quick implementation over the current `develop` branch.
You have it in the new branch `upload-from-inputstream2`:
https://github.com/meganz/sdk/tree/upload-from-inputstream2

Since this feature is not officially available, I can't give you too much support related to it, but I will try to help you when possible if you find any problem using it.

**Comment by dima72** [comment]
Dear Javi,
it is so good to hear from you. I will met you know how upload-from-inputstream2 works.
my other question:
Can you tell whether startUpload  with file name params will work with named pipe passed instead of local file?  If not can you adapt startUpload to read from file handle instead filename? because i can write file into namedPipe.

thanks in advance,

**Comment by dima72** [comment]
Dear Javi, upload-from-inputstream2 is still buggy, maybe we can just fix main trunk allowing to upload from file handle?

I can create NamedPipe, WriteFile data there and ReadFile,but for some reason startUpload internals can not read named pipe data.
If we will manage to do that - our integration product is going to work very stable.
please look at my code:

int BufSize = 512; 
HANDLE hPipe = CreateNamedPipe(L"\\\\.\\pipe\\myNamedPipe", PIPE_ACCESS_DUPLEX,
PIPE_TYPE_BYTE || PIPE_NOWAIT, 2, BufSize, BufSize, 0, NULL);
CheckError(hPipe != INVALID_HANDLE_VALUE, "pipe create error");

HANDLE pipeFileWrite = CreateFile(L"\\\\.\\pipe\\myNamedPipe", GENERIC_WRITE, 0, NULL,
OPEN_EXISTING, FILE_FLAG_WRITE_THROUGH, 0);
CheckError(pipeFileWrite != INVALID_HANDLE_VALUE, "pipeFileWrite INVALID_HANDLE_VALUE");


DWORD a_WrCount = 0;
char a_Buf[2000]; //just fake data 
CheckError(WriteFile(pipeFileWrite, a_Buf, sizeof(a_Buf), &a_WrCount, NULL), "WriteFile Error" );
CloseHandle(pipeFileWrite);

 

 ReadFile(hPipe, a_Buf, sizeof(a_Buf), &a_WrCount, NULL);

**//ReadFile  reads written data from hPipe!!!**

TUploadListener *upload_listener = new TUploadListener();
a_megaApi->startUpload( "\\\\.\\pipe\\myNamedPipe", a_PathNode, a_FileName.c_str(), 0, upload_listener );
upload_listener->wait();

but startUpload fails to send file

**Comment by dima72** [comment]
up

**Comment by javiserrano** [comment]
Hello!

Sorry for the delay.
Unfortunately the regular `startUpload` can't work with pipes because it needs to read several times and seek the file due to integrity checks.

You could upload files reading from a pipe creating a subclass of MegaInputStream, inplementing its functions and using it with the new `startUpload` function in the `upload-from-inputstream2` branch.

Here is a minimal example of how to create a MegaInputStream subclass:
```
class ExampleInputStream : public MegaInputStream
{
public:
    int offset = 0;
    virtual int64_t getSize()
    {
        return 5;
    }

    virtual bool read(char *buffer, size_t size)
    {
        for (size_t i = 0; i < size; i++, offset++)
            *(buffer + i) = '1' + offset;
        return true;
    }

    virtual ~ExampleInputStream() {}
};
```

You could use it this way:
`                    megaApi->startUpload(new ExampleInputStream(), megaApi->getRootNode(), "inputstream.txt", time(NULL));`
_Please notice that the line above contains several memory leaks!!_

That would create a file with the name "inputstream.txt" of 5 bytes with the string "12345" in the root of your Cloud Drive.

I have just tested it and it seems to work correctly.

In your case, you would have to know the size of the file in advance and read from your pipe in your implementation of the `read` function.

If you notice any bug, please report it here providing as many details as possible to be able to help you better.

Regards, Javi.

**Comment by dima72** [comment]
> Unfortunately the regular startUpload can't work with pipes because it needs to read several times and seek the file due to integrity checks.

Can startUpload work with File Handles? In Mega code i can see that you are using file handles.
Can you please make file handle as parameter for startUpload instead of *localPath? IMHO there is no difference if File Handle is Pipe Handle at I/O level.

thanks in advance,
