### ISSUE TITLE
MEGA glitches today

### ISSUE THREAD

**Issue by dima72** [meganz/sdk#125]
I uploaded files with MEGA SDK.

they appeared on remote.

after some minutes on remote, all files are dissapear  as well as directories.( in web interface too )

this problem happens all over again.

**Comment by javiserrano** [comment]
Hi,

Sometimes, due to system maintenance tasks, API servers can be slower or some storage servers can be down for few time. However, those problems should never cause the deletion of nodes.

These inconsistencies are usually due to local cache corruption in the SDK or problems in the webclient. We had some bugs in the past that could cause this effect but files should be visible after a full reload/fetchnodes in these cases.

If you see any problem like this one at any moment, it would be very useful to have the SDK logs from those executions. The command line client `megacli` allows to get debug info (using the `debug` command). Also, you can get logs in your own apps using `MegaApi::setLoggerObject` and `MegaApi::setLogLevel`.

If that's not possible, detailed steps could help us to reproduce the problem and fix it.

Thanks, Javi.
