### ISSUE TITLE
SYNC not working

### ISSUE THREAD

**Issue by aratz-lasa** [meganz/sdk#1286]
Hello,
I use MEGA for saving my programs log. However, even though I have synced my logs folder and mega-cmd-server running, it does not sync well: sometimes, it takes hours to sync, or it doesn't do it directly. 
If you wonder, the log flushes directly every time it writes to the file, and if I check last modification date in the filesystem, it is updated. Even more, if I execute manually "mega-sync", it says it is already synced.

**Comment by aratz-lasa** [comment]
I have just figured out how to make it work. In order to sync it right, I have to kill first mega-cmd-server:
`pkill mega-cmd-server && mega-sync`

**Comment by sergiohs84** [comment]
@aratz-lasa can you provide logs from the `mega-cmd-server` in order to inspect what may happen? I'm aware the SDK delays syncying files that are updated very often, something that usually happens to programs logs. It's a protection to avoid wasting your bandwidth, since the upload will take a while and, in the meantime, the file is changed, so the upload has to start over and over. You might be observing such issue, and a log would confirm the aforementioned theory.

**Comment by maleks4** [comment]
I’m wanted to bypass iCloud 
![BB76D708-85A1-46CB-9B33-E853E2A94B10](https://user-images.githubusercontent.com/53895855/71416564-2f0e5700-268b-11ea-99fc-7d06f70009f3.png)
![Uploading B3AE3EE7-AF3A-4D7B-92D6-AC7F34C4B7CB.png…]()
![Uploading 3FD0128B-9833-4137-847F-F05FC3577F39.png…]()
![Uploading EAF5110B-32BF-4D2F-A52C-122F8FA601DD.png…]()

**Comment by maleks4** [comment]
Bypass icloud

**Comment by sergiohs84** [comment]
This issue is obsolete. If you still observe the issue, please, create a new issue. Thanks
