### ISSUE TITLE
MegaTransferListener.onTransferFinish

### ISSUE THREAD

**Issue by dima72** [meganz/sdk#173]
Dear All,

what is guaranteed way to determine UploadListener that transfer is finished
or startUpload transfer finished?

the reason I'm asking, regardless onTransferFinish is implemented in my UploadListener,
this event sometimes does not happen.

thanks in advance,

**Comment by dima72** [comment]
what means ENABLE_SYNC directive in Mega Api?

**Comment by javiserrano** [comment]
`onTransferFinish` should always be called when the node is added to the MEGA account. That is usually a bit after the transfer has finished, because an API command has to be sent to associate the uploaded data with a node in the account.

There is only one known edge case in which onTransferFinish is not called; when `startUpload` is called with a file that is already added to the transfer queue (could be with a different name but the same contents and modification time).

If this edge case is not the one affecting you, I would need to know if the upload that don't call `onTransferFinish` is from an input stream (that is still a beta feature).

If it isn't the case, please send me a SDK log showing one of those transfers that don't call `onTransferFinish`. You can create an SDK log using `MegaApi::setLogLevel` (please use `MegaApi::LOG_LEVEL_MAX`).

It could contain sensitive data, so please take a look before sending it or send it by email to js [at] mega.co.nz.

ENABLE_SYNC is used to enable/disable the sync engine of the SDK that is used by our MEGAsync app.

**Comment by dima72** [comment]
onTransferFinish I'm having problem with is from an input stream.

please mention where log file resides.

**Comment by javiserrano** [comment]
With the log I mean the output of the app in the console

**Comment by dima72** [comment]
unfortunately can not stream COUT becasue I'm in dll.
can you please share conditional defines directives for compilation.
in my project i use:
WIN32
_DEBUG
WIN32_LEAN_AND_MEAN
USE_SQLITE

**Comment by dima72** [comment]
Dear Javi,

please let me know how can I send you log file with my upload session.
it uses new input stream version of API. Session is always never ends if I upload 18 files with 3 threads.Last file is always keeps waiting for complete.

**Comment by javiserrano** [comment]
Hi,
I have taken a look at your log.
It shows 17 started transfers (`Transfer (UPLOAD) starting` messages) and 17 finished transfers (`Transfer (UPLOAD) finished` messages) so it it doesn't seem to be a low level problem.

Maybe the transfer number 18 doesn't even start and that's why you don't receive the `onTransferFinish` callback. But in that case, the `onTransferStart` callback shouldn't be received in your code.

I will take a deeper look tomorrow to your code. Anyway, it would be good if you could add some logs just before your `startUpload` calls and `onRequestFinish` implementation to confirm the problem. You can use `MegaApi::log` to take advantage of the logging system of the SDK.

If possible, please add also a log in `megaapi_impl.cpp:7853`, next to the comment `//Already existing transfer`. It's the only code path that I can see that would not call transfer callbacks.

**Comment by dima72** [comment]
Dear Javi,

thank you for advising on the problem,
Now it looks that our part was causing internal problem, in fact out logging system, so I apologies for the mess.

**Comment by javiserrano** [comment]
No problem. I'm glad to see that you saw it :-)
Feel free to contact us again if you have more doubts or you see any other problem.
