### ISSUE TITLE
Deleted files still occupy space in metadata

### ISSUE THREAD

**Issue by ReimuNotMoe** [meganz/sdk#2053]
Hello. I'm your Business Account user. Your support dept wasn't able/willing to solve my problems, so I'm here trying to get in touch with your tech guys.

Recently I accidentally uploaded a lot of small files and this made my login process painfully slow. And now I managed to delete them (and cleared trash), but the login process didn't become faster.

A month ago: each new login will download ~300MB of metadata.
Yesterday: each new login will download ~1.1GB of metadata.
Today: each new login will **STILL** download ~1.1GB of metadata.

**If I understand correctly, your approach to store file metadata (the "nodes") is kinda like a sqlite database, i.e. its size won't decrease after deleting inner contents. So maybe you need to perform a trim on the server side.**

**Please help. Since this is a business account, and your support dept is not doing anything helpful.**

![Screenshot_20200617_163405](https://user-images.githubusercontent.com/34613827/84875310-63058a80-b0b8-11ea-80c1-346eb186a396.png)

**Comment by mattw-mega** [comment]
An initial login will download all your metadata and store it in an sqlite database, as you say.   Subsequently you should be resuming your session, rather than logging in.  Resuming your session means the sqlite database can be used, and only changes since last time need to be downloaded.   MEGAsync and MEGAcmd do this automatically (so long as you don't explicitly log out before exiting them - if you do log out then all the sqlite data is deleted, and unusable anyway without the session keys, requiring a new login).

**Comment by ReimuNotMoe** [comment]
Yeah, but I mean the huge JSON file with deleted file entries, downloaded from `g.api.mega.co.nz/cs`
