### ISSUE TITLE
Integrating Mega libs in android studio project

### ISSUE THREAD

**Issue by zelin** [meganz/sdk#217]
I am trying to integrating MegaSdk into the AndroidStudioProject

I have copied the folders in libs containing .so files in src > main > jniLibs > armeabi/libmega.so , x86/libmega.so

i have also copied SDK Class files and have placed them in my project.

Now whenever i do  

						ApiManager.getInstance().mMega = new MegaApiAndroid(Constants.MEGA_APPKEY, "SampleAgent", DirectoryUtils.getMainPath(AuthenticationActivity.this).getAbsolutePath());

It fails to load libmega.so and gives me a crash

megaJNI.swing_module_init Native method not found.

Where to place the so files in android studio and how can i make the project read them

**Comment by zelin** [comment]
Any response to this bug?

**Comment by sergiohs84** [comment]
We are currently using Eclipse + ADT plugin to build the Android app (and the _make_ tool in order to prepare the MegaSDK library).

Unfortunately, we don't have a working project configuration for AndroidStudio yet, but we are actively working on it right now and trying to solve the same issue you've pointed in your first post. Should you find the right setup to use dynamic libraries on AndroidStudioProjects, we will appreciate your comments.

In the meantime, you can try configuring Eclipse as explained here: https://github.com/meganz/sdk/blob/master/examples/android/README.md

**Comment by sergiohs84** [comment]
@zelin: we've just created a configuration for AndroidStudio for our official Android app and the `libmega.so` is successfully loaded by the application.

We also faced the same issue than you during the setup. The actual problem was related to the native library, which was built using the wrong compiler, resulting on linking problems. The `jni/Application.mk` sets `NDK_TOOLCHAIN_VERSION=4.8` to use GCC 4.8 to cross-compile the native library. However, the newest NDK r11 has tagged GCC 4.8 as deprecated and the makefile tries to compile the library using the compiler installed in the system.

To solve the issue, we recommend to keep using the previous version of the NDK: r10e

Finally, you can double-check that the native library is properly packed within the app in the APK. You should find a subfolder for each ABI inside the `libs` folder.

Hope these lines help you to solve your linking problem.

**Comment by zelin** [comment]
Thanks for the reply. However where can i get the R10E libs?

**Comment by sergiohs84** [comment]
There is a new branch named `android-studio` that will eventually be merged into master. It contains a new Android _ExampleApp_ project for AndroidStudio using NDK r10e. Thanks to the new IDE, the whole building is done in 3 simple steps that I encourage you to try (it will cross-compile the MEGA SDK libraries for you). You can follow the instructions from [https://github.com/meganz/sdk/tree/android-studio/examples/android/ExampleApp_AS](url)

However, in case you just need the binaries (and the required auto-generated Java bindings), you can download them from this link: [https://mega.nz/#!zktVFAyS!ZzvOYnU-I6cmKgc3_rA-UIJh98suyLAM6BPF7_57BoM](url)
