### ISSUE TITLE
Downloading from a public folder link

### ISSUE THREAD

**Issue by jaskaranSM** [meganz/sdk#2200]
What is the correct way of downloading from a public folder link? MegaApi.loginToFolder causes the login from Mega Account to be overwritten, This method does fetch the required node, but the transfer is done without the user's account. resulting in using standard download quota. i want to use the Mega Account for folder downloads aswell, MegaApi.getPublicLinkInformation does have a method to get public handle of the folder, but MegaApi.getNodeByHandle returns null with that handle, So i would like to get some help regarding this issue.

**Comment by sergiohs84** [comment]
Hi @jaskaranSM.
You are in the right direction, the `MegaApi.loginToFolder()` is the first step, since you get all the information about the nodes contained in the public folder link. Afterwards, you can use an additional instance of `MegaApi`, logged in into the user's account, to download and/or copy any node from the folder link. However, since those nodes are foreign (belong to another account), you first need to authorize the node, in order to download it with the user's account.
See `MegaNode *authorizeNode(MegaNode *node);` here: https://github.com/meganz/sdk/blob/develop/include/megaapi.h#L14733
Have a nice coding :)

**Comment by jaskaranSM** [comment]
Hi @sergiohs84 
Thanks for the reply. i got folder downloads working with authorizeNode(). btw  i am using python bindings and there seems to be a weird swig error (DirectorMethodException) while calling MegaListener.onTransferTemporaryError, doesnt matter if one overrides this class method or not, it still results in a crash when swig tries to call it. i captured logs with higher logging enabled from MegaSdk . Heres the error log : 
![Screenshot_2020-08-29_12-47-33](https://user-images.githubusercontent.com/37726998/91632233-254ca880-e9fd-11ea-8a13-d240b842740c.png)

**Comment by sergiohs84** [comment]
Glad to know that the authorizeNode() solved your issue :)
