### ISSUE TITLE
java.lang.UnsatisfiedLinkError: mega.dll: Can't find dependent libraries (prebuilt binary on windows 10 64 bit)

### ISSUE THREAD

**Issue by Thepattybeast** [meganz/sdk#240]
Attempting to create a new MegaApiJava on windows 10 64 bit (Using a 32 bit jvm) results in The following errors:

`Native code library failed to load.`
`java.lang.UnsatisfiedLinkError: \libs\mega.dll: Can't find dependent libraries`
`java.lang.UnsatisfiedLinkError: /libmega.so`
`java.lang.UnsatisfiedLinkError: Can't load library: /libs/libmegajava.so`
`java.lang.UnsatisfiedLinkError: \libs\mega.dll: Can't find dependent libraries`
Paths shortened to project directory.

I created a Dependency Walker dump of the mega.dll [here](http://pastebin.com/djqtCNrg).

Dependency Walker Log (Also at the bottom of the pastebin):
`Error: At least one required implicit or forwarded dependency was not found.`
`Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.`
`Error: Modules with different CPU types were found.`
`Warning: At least one delay-load dependency module was not found.`
`Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.`

**Comment by javiserrano** [comment]
Please, install MVC++ 2010 redistributable packages to see if that fixes the problem:

x86:
http://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe

x64:
http://download.microsoft.com/download/A/8/0/A80747C3-41BD-45DF-B505-E9710D2744E0/vcredist_x64.exe

**Comment by Thepattybeast** [comment]
Already had it installed, however I tried both of them and got the same error. #210 mentions a msvcp100d.dll and a msvcr100d.dll which I don't have (I have the normal ones). These are the debug versions and the only way to get them is to install visual studio 2010 right?

**Comment by javiserrano** [comment]
I have just checked it and indeed the prebuilt dll is a debug build, so it requires to install VS2010 :-/
We will try to provide a release version of that dll during the next week. I will update the issue when it's ready. Sorry for the inconvenience.

**Comment by Balgden** [comment]
Since there has been no (visible) progress on https://github.com/meganz/sdk/issues/196, could you please provide a 64bit dll as well?

**Comment by javiserrano** [comment]
We have built new packages with the release version of `mega.dll` and also a 64 bit version.
You can download it here:
https://mega.nz/#!UtkgFZbS!v9aL5DpDyw5jmQljAx3Ns-wvjbYPOsQn-eQKZMx3qqE

Instructions to build your own library and examples have been also updated, including packages with prebuild versions of all dependencies for 32 and 64 bits:
https://github.com/meganz/sdk/blob/master/bindings/java/contrib/vs2010
https://github.com/meganz/sdk/tree/master/examples/java

Take into account that this version of `mega.dll` depends on other dlls (cURL, c-ares, OpenSSL, FreeImage,...). In the previous version, some of the required libraries were statically linked and some weren't needed (we have recently started building the SDK with cURL instead of WinHTTP by default to solve connectivity issues). It could be required to add the path that contains those DLLs to your `PATH` environment variable to allow the JRE to find them (it's commented in the README now).

**Comment by Balgden** [comment]
Thank you very much!
