### ISSUE TITLE
[Question] Binding for GO Lang?

### ISSUE THREAD

**Issue by stormenergy91** [meganz/sdk#2618]
Hi, do you have any plans to release a binding for the GO language?

**Comment by jaskaranSM** [comment]
Hi, If you only care about the download functionality I have made a CGO based wrapper over MegaSDK, [here](https://github.com/jaskaranSM/megasdkgo) ,Its very basic and only exports the login and download stuff of SDK to golang, as these two are the only things I had required for my project.  To make things even more simpler, I have wrapped it into an HTTP server daemon too so that it can be controlled over HTTP by any language that supports HTTP requests. That one is [here](https://github.com/jaskaranSM/megasdkrest)

**Comment by sergiohs84** [comment]
Thanks for the suggestion. Binding for Go will be considered to be added through SWIG, as the rest of bindings, starting next year. Thanks
