### ISSUE TITLE
python integration to upload video/image and get direct link to play/display video/image

### ISSUE THREAD

**Issue by SnpGroup** [meganz/sdk#2688]
can you please guide me to documentation for python integration to upload video/image and get direct link to play/display video/image?

I could found simple import example, but how to use it is missing.

**Comment by sergiohs84** [comment]
Hi @SnpGroup . 

First of all, be aware that any _direct link_ to a file in MEGA will require a MEGA client in order to decrypt the downloaded/streamed file. For instance, a file link like https://mega.nz/<public_handle>#<key> provides access to the file, but it still needs decryption.
Note that our website allows to do so by modifying the link (note the `embed/`) : https://mega.nz/embed/<public_handle>#<key> will make it possible.

That said, my suggestion is that first you import/upload the file to your cloud and later on you can create a link by calling the function `exportNode()`. It should provide you the link.

If you are running our command-line example through Python as explained [here](https://github.com/meganz/sdk/tree/master/bindings/python#run-megacli-with-python), you can:

1. login <user> <password>
2. put <local_file>
3. export <uploaded_file>
