### ISSUE TITLE
Android Studio Compilation Failed

### ISSUE THREAD

**Issue by ehsan75** [meganz/sdk#269]
Error:error: cannot find out size of long.
make: *** [curl/curl-7.48.0/curl-config] Error 1
:app:megaSDK FAILED

**Comment by sergiohs84** [comment]
@ehsan75 could you provide some context for the error? like what is your toolchain configuration, version of Android Studio, steps you've already tried...

Usually, the error you're reporting is due to not configure the cURL library properly. The megaSDK for Android requires to use the Android Native Development Kit (NDK), and currently the latest supported version is the r10e.

A new NDK version has been recently release (r11). It tags GCC 4.8 as obsolete, which is the compiler used by our compilation scripts. Since the new NDK doesn't include 4.8, it uses the system compiler (which is not a cross-platform compiler) and configures the cURL library to be used on 64bits machine. That's exactly the issue you're posting: _cannot find out size of long_

By now, we strongly recommend to stay at NDK r10e in case you don't want to adapt compilation scripts by your own.

**Comment by ehsan75** [comment]
Now I figure out the reason and resolved that issue but now your script points zip which is not present on server 
--------------------
ehsan@ehsan-Inspiron-3542:~/ExampleApp_AS/app/src/main/jni$ make
wget -O sqlite/sqlite-amalgamation-3120000.zip http://www.sqlite.org/2016/sqlite-amalgamation-3120000.zip
--2016-04-25 20:33:02--  http://www.sqlite.org/2016/sqlite-amalgamation-3120000.zip
Resolving www.sqlite.org (www.sqlite.org)... 67.18.92.124, 2600:3c00::f03c:91ff:fe96:b959
Connecting to www.sqlite.org (www.sqlite.org)|67.18.92.124|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-25 20:33:03 ERROR 404: Not Found.

make: *** [sqlite/sqlite-amalgamation-3120000.zip_verified] Error 8

**Comment by sergiohs84** [comment]
Actually, we just noticed that SQLite.org has removed the 3120000 version that we were using until now.

Please, pull the latest changes from the repository to update to 3120200. The latest commit is:  af392b2

Thanks for reporting the issue.
