### ISSUE TITLE
How many ACTIVE sessions concurrent

### ISSUE THREAD

**Issue by ElegantWang** [meganz/sdk#374]
Hi, I have a question about session.that is,
How many ACTIVE sessions one account can have concurrent?

**Comment by sergiohs84** [comment]
Currently, MEGA does NOT impose any restriction on the number of concurrent active sessions for the same user account. 
Thanks

**Comment by ElegantWang** [comment]
Thanks.But I encountered a problem in my test application.
Invoke mega api “login” over 200 times without “logout” and get an api error: Rate limit exceeded.
Then I logout one or several session and can login again.

**Comment by sergiohs84** [comment]
200 active sessions seems too many sessions, indeed. Why would you like to have such a high number of concurrent sessions?

Regardless your motivation, there's no limit on the number of sessions, but since your test application is hitting our servers too much, they are probably responding with the error you mentioned: rate limit exceeded.

Are you calling `login` from the same instance of your app? or is it from 200 independent instances?

Should you like to have a look at your currently active sessions (and maybe close some of them), you can do it from the website [here](https://mega.nz/#fm/account/history) or in the `Account view > Close other sessions` in the mobile app (except for iOS, which it's a coming feature).

Regards

**Comment by ElegantWang** [comment]
Indeed I saw some active sessions whoes "Most recent activity" are  "2016-03-20 15:02..." from [here](https://mega.nz/#fm/account/history) because I forget logout in my application.

It seems there is no timeout limit for these sessions. So I test the login in the same test application.

Thanks.
