### ISSUE TITLE
megacli sync stalled with internet disconnections

### ISSUE THREAD

**Issue by latot** [meganz/sdk#447]
Hi all, well, this happen a lot when you store big files, normally megacli can resume downloads/uploads when occurs an internet disconnection, but sadly don't always works, and when it happen the sync is stalled, and i can't found any way to can stop/resume it, even if exist a command for it some times when this happen the app is stalled too, you can't write, so the only way is close megacli and sync again, but when you have 20 files of 4GB or more this never ends, because the probability of have an internet disconnection in that long time is too high, so in the first file you will need repeat this every time...

So summarizing:
- megacli don't always resume in a internet disconnection
- megacli with some internet disconnections is freeze

Optional point:
- megacli don't have a way to can stop/resume sync

Thx. Cya.

**Comment by sergiohs84** [comment]
@latot thank you for the analysis and reporting, it's a very good feedback.

We are aware of issues when the Internet connection is lost during a transfer, which could affect the sync feature in megacli. The problem is that the way to identify the disconnection is not cross-platform. We've recently merged some changes into develop (https://github.com/meganz/sdk/pull/434) that should retry transfers in approximately 2 minutes after the blocking situation is detected. If you could give a try and provide some feedback, it would be very appreciated. 

Also note that megacli is just an example to show up the usage of the SDK at low level. Hence, it shouldn't be used in production setups.

If you want to synchronize folders between different computers, we encourage you to use MEGAsync, which provides a friendly-to-use graphical interface and doesn't suffer from the issues you reported.

Best regards

**Comment by latot** [comment]
Hi!, i test this and seems works!, only to be sure, the changes works in linux?

Only in my personal opinion, i don't like use gui with some type of apps, or in the inverse order, i only like gui with some complex or required apps, like audio/video editors, etc. But with apps for download, or manage this type of data i normally prefer terminal apps.

in some way this issue affect the download theme, not only sync.
Anyway, thx for the recommendation of MEGAsync, and a little question, it provides a terminal interface?

Thx. Cya.

**Comment by javiserrano** [comment]
Hi,

Yes, the changes should work on all platforms. Basically, we detect that there is a pending request and that there is no network activity during a reasonable amount of time. Retrying the request wouldn't be good in many cases because some requests can take a lot of time and we would just restart them in a loop.

So, when that situation is detected, a new request is sent to the server to know if it's busy processing the previous one (in that case we have to keep waiting) or if it is not (in that case the request or the response was lost in the network and a retry is needed). We know that the second request can't take much time so we have a short timeout for it to prevent that it also gets blocked.

MEGAsync doesn't provide a terminal interface, but we are working on a more complete command-line app. It's not totally finished yet but you can take a look if you want to its current state:
https://github.com/meganz/sdk/tree/megacliAPI_transfers

I'm not very familiar with that development but I think that configuring that branch of the SDK with the option `--enable-megacmd` should be enough to build the new tool (in `examples/mcmd`).

**Comment by latot** [comment]
well, after test this time i can confirm this issue is done, if you want do the optional point i think can be better a new issue. If i miss something please reopen it.

Thx. Cya.
