### ISSUE TITLE
Libraries reupload

### ISSUE THREAD

**Issue by tymoteuszborkowski** [meganz/sdk#527]
Hi, 
is it possible to reupload prebuilt libraries for android app? Unfortunately [this]( https://mega.nz/#!lwVGUACR!3fBAdhhfeabHK4HouiMXytM8YW_AU_JVSjdDEdLuqIY) link is no longer avaliable. 

Thank you.

**Comment by sergiohs84** [comment]
Hi @tymoteuszborkowski 

Thank you for reporting the broken link. We've just updated the prebuilt libraries for the Android examples, both with AndroidStudio and with Eclipse+ADT.

Please, let us know if the issue is solved.
Thanks

**Comment by tymoteuszborkowski** [comment]
Thanks for fast reply! Problem is solved of course :)

**Comment by javiserrano** [comment]
A possible way would be to use the new `SynchronousRequestListener` (in the `develop` branch of the SDK). But, unfortunately, we don't generate Java bindings for them yet because we haven't tested them on Java. You could generate them by removing the line:

`%ignore mega::SynchronousRequestListener;` 

in `bindings/megaapi.i` (`develop` branch) and rebuilding.

However, blocking a thread that way is usually a bad idea. Doing it in the main thread of any graphical app would hang your app until the request finishes, so you would have to do it in a worker thread.

A better approach in most cases is to register a listener and continue the processing when the request finish. You can see an example of this usage in `examples/java/src/nz/mega/bindingsample/SwingExample.java` where a listener is registered for the `login` request, and the next request (`fetchNodes`) is sent when the login completes (in the `onRequestFinish` callback of that listener).

You can also set a listener for all events (using `MegaApi::addListener`) and centralize your logic in that object. MEGAsync uses that approach to manage most events in a single object (`MegaApplication`):
https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/MegaApplication.cpp#L623
