### ISSUE TITLE
Use https in megacli

### ISSUE THREAD

**Issue by shinchiro** [meganz/sdk#528]
Hello,

Is it possible to force using https in transfer process (mostly in uploading) in megacli?

**Comment by javiserrano** [comment]
Hi,
It's not possible to force the usage of HTTPS for transfers in `megacli` yet without rebuilding it.

You can force it by changing this line:
`    usehttps = false;`

by this one:
`    usehttps = true;`

in the constructor of MegaClient (`src/megaclient.cpp`) and rebuilding megacli.
Anyway, it's only recommended to use it when there are problems with HTTP due to a firewall, a proxy or something like that. It doesn't add any security because all transfer data is already end-to-end encrypted.

If you have problems with port 80, another option is to change the value of the flags: `usealtdownport` and `usealtupport` (also in the constructor of MegaClient), that forces the SDK to use the port 8080 for uploads or downloads.

**Comment by shinchiro** [comment]
Thanks for the info.

> Anyway, it's only recommended to use it when there are problems with HTTP due to a firewall, a proxy or something like that

pretty much of this
