### ISSUE TITLE
On iOS, crash when dealloc the MegaSDK instance

### ISSUE THREAD

**Issue by sylverb** [meganz/sdk#57]
When deallocation MegaSDK instance, a DELETE request is started but it crashes in posixthread.cpp

    PosixMutex::~PosixMutex() <- EXC_BAD_ACCESS (code = 1, address = 0x0)
    {
        delete mutex;
        pthread_mutexattr_destroy(attr);
        delete attr;
    }

![Image of crash](http://i.imgur.com/zIs23aQ.png)

**Comment by javiserrano** [comment]
Hello and happy new year!

The problem seems to be that `attr` is being destroyed even if it hasn't been initialized (non recursive mutexes don't use it). This commit should fix the crash:
https://github.com/meganz/sdk/commit/e9e06d8227549dc6f125ac6c08e3bb6c476c31f4

I will close the issue as soon as one of our iOS developers confirm that it's OK, or if you can confirm that it's fixed, feel free to close it.

Thank you!

**Comment by sylverb** [comment]
Hi !
Happy new year !
It fixes the crash, thanks a lot ! :+1:
