### ISSUE TITLE
[Java] Getting public links

### ISSUE THREAD

**Issue by Neeqstock** [meganz/sdk#611]
Hello,  
I'm developing a Java app in which I need to get the public links for the files in my MEGA cloud, to let other people download them.

The problem is that until I generate the link via _right-click+"get link"_ in the browser for each file, the method _MegaNode.getPublicLink()_ returns "null".  

Since in my cloud there are a lot of file and there will be more in the future, I cannot manually generate them all, I would become mad :). So, my question is:  
is there a way to automatically generate the links for all the files?  
Or is there another workaround for my issue?  
  
Thanks for your support.

**Comment by javiserrano** [comment]
Hello,
`MegaNode.getPublicLink()` only returns public links for already exported nodes.
To get a public link of a node that has not been exported yet, you should use the C++ function `MegaApi::exportNode`. So, in your case, `MegaApiJava::exportNode`, `MegaApiSwig::exportNode` or `MegaApiAndroid::exportNode` depending on your platform.

You can also use that function with already exported nodes. The only inconvenience is that it's an asynchronous function (you have to get the result in the `onRequestFinish` callback) because it's needed to access the network if the node is not exported yet.

**Comment by Neeqstock** [comment]
Thanks, solved my doubts.
