### ISSUE TITLE
temp download

### ISSUE THREAD

**Issue by not83** [meganz/sdk#65]
Is there a way to implement an option download mega files from my MEGA account but have them deleted after or have them streamed some how?

Looking to have a way to access them from the command line (Linux terminal) but not have them downloaded. 

Looking to have say 50 GB's MEGA data on a say 20 GB's computer

**Comment by javiserrano** [comment]
Hi!

There is a function `MegaApi::startStreaming` in `megaapi.h` that provides the data as it's downloaded without saving it to a file. However, I'm not sure if that's what you want because you would have to create your own app to take advantage of it.

I think that you could use our example filesystem driver for Linux based on FUSE. It can mount the MEGA account (or any subfolder) in a local folder. That way you could access your files and they would be downloaded on demand, without saving any data to the local storage.

The current implementation is just an example. It doesn't allow file writes (uploads), just downloads, and It doesn't have any optimization like a local cache that could make it faster, but if you only want to access your files and you have a fast Internet connection I think that it could be useful for you.

Please take a look at the README.md file in the `examples/linux` folder to know how to build this example app. If you have problems to do it, let me know.

**Comment by not83** [comment]
Awesome! Speedy reply. I will check that out for sure. Thanks very much. This will mean I can keep AWS away and use MEGA
