### ISSUE TITLE
Unsatisfied link error when compiling with maven

### ISSUE THREAD

**Issue by A7F** [meganz/sdk#661]
Hi, I'm trying to run my project on my IDE compiling it with maven... I succesfully generated libmegajava.so as your instructions explains but I have no idea on how to use them with maven: where do I have to put them? I think maven actually don't include it properly in the project.

This is the only error I'm getting:
```
Exception` in thread "main" java.lang.UnsatisfiedLinkError: com.farounipv.nz.mega.sdk.megaJNI.swig_module_init()V
	at com.farounipv.nz.mega.sdk.megaJNI.swig_module_init(Native Method)
	at com.farounipv.nz.mega.sdk.megaJNI.<clinit>(megaJNI.java:1032)
	at com.farounipv.nz.mega.sdk.MegaApi.<init>(MegaApi.java:43)
	at com.farounipv.nz.mega.sdk.MegaApiJava.<init>(MegaApiJava.java:136)
	at com.farounipv.nz.mega.bindingsample.CrudExample.<init>(CrudExample.java:83)
	at com.farounipv.nz.mega.bindingsample.CrudExample.main(CrudExample.java:88)
```

is it an issue related to my pom file which has to specify the target library? How do I include them? Is it like including a local jar file (so I first have to install the .so file and then add the dependency)?

EDIT:
I tried using in my main class
`System.load("/usr/lib/libmegajava.so");`
inside a try-catch. It seems working but I still get the error UnsatisfiedLinkError... so I wonder what is going on

**Comment by javiserrano** [comment]
It's probably too late :-/ but I think that the problem was that you have put our Java classes into a different package `com.farounipv.nz.mega.sdk` and the native library is built to work with classes on the package `nz.mega.sdk`. If Java classes are moved to a different package, the build of the native library should be changed accordingly, at least in the file `bindings/java/include.am` before the configuration and the build of the SDK.
