### ISSUE TITLE
Error building with PHP Bindigs

### ISSUE THREAD

**Issue by latot** [meganz/sdk#73]
Hi, when i try to compile with php binding i got this error:

https://gist.github.com/latot/55015ab73cfa1706c2bb

Thx.

**Comment by javiserrano** [comment]
Hi,

Thank you for reporting the problem.
The compilation fails in code generated by SWIG.
The problem is probably due to an incompatibility between your version of SWIG and your version of PHP.

Unfortunately, I can't reproduce it in my computer.
Are you using a custom build of PHP or SWIG? or default packages from official repos?
Which version of SWIG and PHP are you using?
Which is your Linux distro?

Regards, Javi.

**Comment by latot** [comment]
Hi, i'm using gentoo 64, swig-2.0.9 and php-5.5.22, and i'm using the stable versions. thx.

**Comment by javiserrano** [comment]
According to this issue:
https://github.com/unbit/uwsgi/issues/654

it seems that PHP is built with ZTS enabled on Gentoo.

In the changelog of SWIG:
http://www.swig.org/Release/CHANGES

there is this statement for version 2.0.10:
```2013-01-08: olly [PHP] Fix to work with a ZTS build of PHP (broken in 2.0.7).```

So since version 2.0.7 to version 2.0.10 SWIG wouldn't work with ZTS enabled.
I think that the easier solution would be to update SWIG (if there is a newer version available for your distro) or build the last version of SWIG downloading the code in their web or their repo:
http://www.swig.org/download.html
https://github.com/swig/swig

**Comment by latot** [comment]
Thx, i updated to swig-2.0.12 and works :D

**Comment by javiserrano** [comment]
Great! :-D
If you find any other problem, please let us know.
