### ISSUE TITLE
Please share megacli and megasimplesync for Windows

### ISSUE THREAD

**Issue by supick** [meganz/sdk#77]
Hello, I'm not good at coding and can't build sdk in Windows, could you please share built version include megacli.exe and megasimplesync.exe? It's easier to use command line than official sync app.
Thank you very much!

**Comment by javiserrano** [comment]
Hello. The build of `megacli` and `megasimplesync`is already supported on Windows with MinGW.
Please check the file `Makefile.win32` at the root of the repository.
Is it OK for you or would you prefer a Visual Studio solution?

**Comment by supick** [comment]
Thank you for your reply. I tried to install MinGW and follow instruction in Makefile.win32 before posting here, but I'm a noob and can't make it work :(

**Comment by wizzard** [comment]
Hello, I compiled and uploaded megacli and megasimplesync Windows binaries, here is the link: https://mega.nz/#!0FM2WBAB!rNndUBqwqqUi8FFuB5Cvwy4mp1CVE7yUEgTyrRbTICE

Please note, that in order to run executables, you need to have a few additional dll's, which I include in the archive. Just make sure dll's and exe files are in the same folder.

**Comment by supick** [comment]
Hi, thank you very much.
