### ISSUE TITLE
How to monitor transfer rates / speeds in mega-cmd?

### ISSUE THREAD

**Issue by entr** [meganz/sdk#874]
I think I looked everywhere before posting.

I wanted to see how my connectivity performs and found that `$ mega-transfers` will only report PROGRESS and STATE. 

Also is there a way to monitor transfers similar to how [htop](https://github.com/hishamhm/htop) works, or even `top` for that matter?

**Comment by polmr** [comment]
Hi @entr I'm afraid there's no way to see transfer speed right now. However since that's an useful feature and given the interest we'll add it to the roadmap. We'll need however to be able to select which columns should appear.

Regarding top ... There's no interactive util such as that, but in Linux, you can always do something like (with your own parameters):
```
watch mega-transfers --limit=20 --path-display-size=30
```

**Comment by entr** [comment]
@polmr thank you for the quick reply. Nice tip using `watch`.  Cheers!
